// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi62G7s0eXnCzwbDYYDIj8yDF0drF0_2M',
    appId: '1:1022060321341:android:1d535f74130f9e28122854',
    messagingSenderId: '1022060321341',
    projectId: 'gatsbyrideshare',
    storageBucket: 'gatsbyrideshare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfjn2yfjBGo4armn1iI7l_LPwzh7uVOEk',
    appId: '1:1022060321341:ios:efcbab779994c277122854',
    messagingSenderId: '1022060321341',
    projectId: 'gatsbyrideshare',
    storageBucket: 'gatsbyrideshare.appspot.com',
    androidClientId:
        '1022060321341-a480lq87svbk3m48oqice5v9ujbgn8nj.apps.googleusercontent.com',
    iosClientId:
        '1022060321341-66bst7cav86e9t8tpo73jls03qke9ngj.apps.googleusercontent.com',
    iosBundleId: 'driver.getride.taxi',
  );
}
